config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index do
        scope 'user', module: 'user' do
          resource :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
        end
      end
      resources :auth_tokens, only: :create
      resources :registrations, only: :create

      scope 'user/self', as: 'user', module: 'user' do
        resources :courses, only: :index, controller: :participated_courses
      end

      scope 'user/:id', as: 'authored', module: 'user' do
        resources :courses, only: :index, controller: :authored_courses
      end
    end
  end

  resources :courses, only: [:index, :show] do
    resource :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
    resources :lessons, except: [:edit, :update]
  end

  namespace :users do
    resource :profile, only: [:edit, :update], controller: :profile
    resources :courses
    resources :activities, only: :index
  end

  scope module: 'users' do
    resource :dashboard, only: :show

    scope '/lessons/:lesson_id' do
      resources :homeworks, only: [:show, :index, :create] do
        member do
          put 'approve', to: 'homeworks#approve'
          put 'reject', to: 'homeworks#reject'
        end
      end
    end
  end

  resources :lessons, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :homeworks, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  post '/courses/:course_id/participants/:user_id/expel', to: 'course_expulsions#create', as: :expel_course_participant

  root 'courses#index'
end

app/models/user.rb
# rubocop: disable Style/RedundantSelf
class User < ActiveRecord::Base
  rolify
  include Omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:vkontakte, :twitter]

  has_one  :profile, dependent: :destroy
  has_many :social_profiles, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :course_users, dependent: :destroy
  has_many :participated_courses, through: :course_users, source: :course
  has_many :lessons, dependent: :destroy
  has_many :homeworks, dependent: :destroy
  has_many :feeds, class_name: 'Activity', foreign_key: :recipient_id, dependent: :destroy
  has_many :actions, class_name: 'Activity', foreign_key: :owner_id, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save  :ensure_authentication_token
  after_create :create_user_profile

  accepts_nested_attributes_for :profile

  delegate :first_name, :last_name, to: :profile, allow_nil: true

  def full_name
    first_name + ' ' + last_name
  end

  def participate_in?(course)
    course_users.exists?(course_id: course.id)
  end

  def expelled?(course)
    course_users.find_by(course_id: course.id).try(:expelled)
  end

  private

  def create_user_profile
    return if profile
    build_profile
    profile.save(validates: false)
  end

  def ensure_authentication_token
    return unless self.authentication_token.blank?
    self.authentication_token = generate_authentication_token
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.exists?(authentication_token: token)
    end
  end
end

app/controllers/api/v1/user/authored_courses_controller.rb
class Api::V1::User::AuthoredCoursesController < Api::V1::BaseController
  def index
    respond_with_success User.find(params[:id]).courses
  end
end

app/controllers/api/v1/user/base_controller.rb
class Api::V1::User::BaseController < Api::V1::BaseController
  before_filter :authenticate_user!

  private

  def authenticate_user!
    user = User.find_by(authentication_token: params[:auth_token])

    raise NotAuthorized unless user.present?

    sign_in user, store: false
  end
end

app/controllers/api/v1/user/course_subscriptions_controller.rb
class Api::V1::User::CourseSubscriptionsController < Api::V1::User::BaseController
  before_action :find_course

  def create
    authorize! :subscribe, CourseUser
    result = ManageUserSubscriptionsService.subscribe(@course, current_user)
    form_respond result
  end

  def destroy
    authorize! :unsubscribe, CourseUser
    result = ManageUserSubscriptionsService.unsubscribe(@course, current_user)
    form_respond result
  end

  private

  def form_respond(result)
    if result.success?
      respond_with_success result.message
    else
      render json: { success: false, message: result.message }, status: result.status
    end
  end

  def find_course
    @course ||= Course.find(params[:course_id])
  end
end

app/controllers/api/v1/user/participated_courses_controller.rb
class Api::V1::User::ParticipatedCoursesController < Api::V1::User::BaseController
  def index
    courses = current_user.participated_courses
    respond_with_success courses
  end
end

app/controllers/users/activities_controller.rb
class Users::ActivitiesController < Users::BaseController
  PER_PAGE = 9

  def index
    @activities = current_user.feeds.includes(:trackable, owner: [:profile]).recent.page(params[:page]).per(PER_PAGE).decorate
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :find_comment, only: :destroy
  authorize_resource

  def create
    comment = current_user.comments.build(permitted_params)
    comment.commentable = parent

    if comment.save
      flash.now[:success] = 'Comment was succesfully saved'
    else
      flash.now[:error] = 'Something goes wrong'
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def parent
    @parent ||=
      if params[:lesson_id].present?
        Lesson.find(params[:lesson_id])
      elsif params[:homework_id].present?
        Homework.find(params[:homework_id])
      end
  end

  helper_method :parent

  def permitted_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/users/courses_controller.rb
class Users::CoursesController < Users::BaseController
  before_action :find_course, only: [:edit, :update, :destroy]
  authorize_resource

  def new
    @course = current_user.courses.build
  end

  def create
    @course = current_user.courses.build(course_params)

    if @course.save
      redirect_to dashboard_path, notice: 'Создан новый курс.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to dashboard_path, notice: 'Курс успешно обновлен.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy

    redirect_to dashboard_path, notice: 'Курс удален!'
  end

  private

  def course_params
    params.require(:course).permit(:title, :visible, :picture)
  end

  def find_course
    @course = Course.find(params[:id])
  end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < ApplicationController
  authorize_resource class: false

  def show
    @dashboard = DashboardPresenter.new current_user, params
  end
end

app/controllers/users/homeworks_controller.rb
class Users::HomeworksController < Users::BaseController
  before_action :find_homework, only: [:show, :approve, :reject]
  authorize_resource

  def show
    @comment_for_reject = current_user.comments.build
  end

  def index
    @homeworks = lesson.homeworks.includes(:user)
  end

  def create
    @homework = lesson.homeworks.build(homework_params)
    @homework.user = current_user
    render :new unless @homework.save
  end

  def approve
    authorize! :approve, Homework
    @homework.approve!
    flash.now[:success] = 'Homework was approved!'
  end

  def reject
    authorize! :reject, Homework
    result = Homeworks::RejectService.perform(@homework, current_user, reject_params[:body])

    unless result.success?
      @comment_for_reject = result.comment_for_reject
      flash.now[:alert] = 'Please comment homework, when rejecting.'
    end
  end

  private

  def find_homework
    @homework = Homework.find(params[:id])
  end

  def homework_params
    params.require(:homework).permit(:body)
  end

  def reject_params
    params.require(:comment).permit(:body)
  end

  def lesson
    @lesson ||= Lesson.find(params[:lesson_id])
  end
  helper_method :lesson
end

app/controllers/users/lessons_controller.rb
class Users::LessonsController < Users::BaseController
  before_action :find_lesson, only: [:destroy]

  def new
    @lesson = course.lessons.build
  end

  def create
    @lesson = course.lessons.build(lesson_params)
    @lesson.user_id = current_user.id

    if @lesson.save
      redirect_to dashboard_path, notice: 'Создан новый Урок.'
    else
      render :new
    end
  end

  def destroy
    @lesson.destroy

    redirect_to dashboard_path, notice: 'Урок удален!'
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :position, :description, :notes, :homework, :picture)
  end

  def find_lesson
    @lesson = Lesson.find(params[:id])
  end

  def course
    @course = Course.find(params[:course_id])
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < Users::BaseController
  authorize_resource

  def edit
  end

  def update
    if current_user.update(user_params)
      sign_in current_user, bypass: true
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, profile_attributes: [:first_name, :last_name])
  end
end

app/views/users/dashboards/_coach_panel.html.haml
.col-md-9
  .box.box-primary
    .box-header.with-border
      %h3.box-title Recently Added Courses
      .box-tools.pull-right
        %button.btn.btn-box-tool{'data-widget' => 'collapse'}
          %i.fa.fa-minus
        %button.btn.btn-box-tool{'data-widget' => 'remove'}
          %i.fa.fa-times
    .box-body
      %ul.products-list.product-list-in-box
        - @dashboard.courses.each do |course|
          %li.item
            .row
              .col-md-6.col-xs-12
                .product-img
                  = image_tag(course.picture.admin_thumb, alt: 'Course picture')
                .product-info
                  %h4.product-title
                    = link_to course_path(course) do
                      = course.title
                  %span.product-description
                    = l(course.created_at, format: '%d %B %Y')
                  %hr
              .col-md-1.col-xs-12
                - if course.visible?
                  %span.label.label-success
                    Visible
                -else
                  %span.label.label-danger
                    Invisible
              .col-md-5.col-xs-12
                .btn-group.pull-right
                  = link_to 'Add lesson', new_course_lesson_path(course), class: 'btn btn-primary'
                  = link_to 'Edit', edit_users_course_path(course), class: 'btn btn-primary'
                  = link_to 'Delete', users_course_path(course), method: :delete, data: {confirm: 'Are you shure?'}, class: 'btn btn-primary'
            .row
              .col-md-8.col-xs-12
                %b
                  Количество уроков:
                = course.lessons.length
                %br
                %table.table.table-hover.fa-hover
                  - course.lessons.each do |lesson|
                    %tr
                      %td
                        .product-title
                          = link_to lesson.title, course_lesson_path(course, lesson)
                      %td
                        = lesson.date.strftime('%x')
                      %td
                        .btn-group.pull-right
                          = link_to 'Homeworks', homeworks_path(lesson), class: 'btn btn-xs btn-primary'
                      %td
                        .btn-group.pull-right
                          = link_to 'Delete', course_lesson_path(course, lesson), method: :delete, data: {confirm: 'Are you shure?'}, class: 'btn btn-xs btn-primary'
                = link_to 'Показать все уроки', course_lessons_path(course), class: 'btn btn-primary'
              .col-md-4.col-xs-12
                %b
                  Участники:
                %table.table.table-hover.fa-hover
                  - course.participants.includes(:profile).each do |participant|
                    %tr
                      %td
                        .product-title
                          = participant.full_name if participant.first_name.present?
                      %td
                        .product-title
                          = participant.email if participant.email.present?
                      %td
                        %div{ id: "expel-button-#{course.course_user_id(participant)}", style: ('display: none;' if participant.expelled?(course)) }
                          = link_to 'Отчислить', expel_course_participant_path(course, participant), method: :post, remote: true, class: 'btn btn-xs btn-primary'
                        %div{ id: "disabled-expel-button-#{course.course_user_id(participant)}", style: ('display: none;' unless participant.expelled?(course)) }
                          = link_to 'Отчислить', expel_course_participant_path(course, participant), method: :post, remote: true, class: 'btn disabled btn-xs btn-primary'
    .box-footer.text-center
      = paginate @dashboard.courses

app/views/users/dashboards/_student_panel.html.haml
.col-md-9
  .box.box-primary
    .box-header.with-border
      %h3.box-title Participated Courses
      .box-tools.pull-right
        %button.btn.btn-box-tool{'data-widget' => 'collapse'}
          %i.fa.fa-minus
        %button.btn.btn-box-tool{'data-widget' => 'remove'}
          %i.fa.fa-times
    .box-body
      %ul.products-list.product-list-in-box
        - @dashboard.participated_courses.each do |course|
          %li.item
            .row
              .col-md-9.col-xs-12
                .product-img
                  = image_tag(course.picture.admin_thumb, alt: 'Course picture')
                .product-info
                  %h4.product-title
                    = link_to course_path(course) do
                      = course.title
                  %span.product-description
                    = l(course.created_at, format: '%d %B %Y')
              .col-md-3.col-xs-12
                - if current_user.expelled?(course)
                  = link_to 'Вы отчислены', course_subscriptions_path(course), method: :post, remote: true, class: 'btn disabled btn-danger btn-block btn-flat'
                -else
                  %div{ id: "subscription-button-#{course.id}", style: ('display: none;' if current_user.participate_in?(course)) }
                    = link_to 'Подать заявку', course_subscriptions_path(course), method: :post, remote: true, class: 'btn btn-success btn-block btn-flat'
                  %div{ id: "unsubscription-button-#{course.id}", style: ('display: none;' unless current_user.participate_in?(course)) }
                    = link_to 'Отписаться', course_subscriptions_path(course), method: :delete, remote: true, class: 'btn btn-warning btn-block btn-flat'
    .box-footer.text-center
      = paginate @dashboard.participated_courses

app/views/users/dashboards/show.html.haml
= provide(:title, 'Dashboard')

%section.content-header
  %h1
    Dashboard
%section.content
  .row
    .col-md-3
      .box.box-primary
        .box-body.box-profile
          = image_tag 'user2-160x160.jpg', class: 'profile-user-img img-responsive img-circle', alt: 'User profile picture'
          -if current_user.first_name
            %h3.profile-username.text-center= current_user.full_name
          %p.text-muted.text-center
            = @dashboard.user.email
          - if current_user.has_role? :coach
            %ul.list-group.list-group-unbordered
              %li.list-group-item
                %b Courses
                %a.pull-right
                  = @dashboard.user.courses.count
            = link_to new_users_course_path, class: 'btn btn-primary btn-block' do
              %b Create new course
    - if current_user.has_role? :coach
      = render 'coach_panel'
    - else
      = render 'student_panel'