config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index do
        scope 'user', module: 'user' do
          resource :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
        end
      end
      resources :auth_tokens, only: :create
      resources :registrations, only: :create

      scope 'user/self', as: 'user', module: 'user' do
        resources :courses, only: :index, controller: :participated_courses
      end

      scope 'user/:id', as: 'authored', module: 'user' do
        resources :courses, only: :index, controller: :authored_courses
      end
    end
  end

  resources :courses, only: [:index, :show] do
    resource :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
    resources :lessons, except: [:edit, :update]
  end

  namespace :users do
    resource :profile, only: [:edit, :update], controller: :profile
    resources :courses
    resources :activities, only: :index
  end

  scope module: 'users' do
    resource :dashboard, only: :show

    scope '/lessons/:lesson_id' do
      resources :homeworks, only: [:show, :index, :create] do
        member do
          put 'approve', to: 'homeworks#approve'
          put 'reject', to: 'homeworks#reject'
        end
      end
    end
  end

  resources :lessons, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :homeworks, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  post '/courses/:course_id/participants/:user_id/expel', to: 'course_expulsions#create', as: :expel_course_participant

  root 'courses#index'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  include AASM

  belongs_to :user
  belongs_to :course
  has_many :homeworks, dependent: :destroy
  has_many :activities, as: :trackable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  scope :by_position, -> { order(position: :asc) }

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
  validates :position, presence: true

  mount_uploader :picture, LessonPictureUploader

  before_create :increment_positions
  after_destroy :decrement_positions

  aasm column: :state do
    state :pending_conduction, initial: true
    state :pending_for_materials
    state :materials_uploaded

    event :conduct_lesson do
      transitions from: :pending_conduction, to: :pending_for_materials
    end

    event :send_materials, after_commit: [:send_lesson_notification, :create_lesson_materials_uploaded_activity] do
      transitions from: :pending_for_materials, to: :materials_uploaded
    end
  end

  def user_homework(user)
    homeworks.where(user: user).first
  end

  private

  def increment_positions
    Lesson.where(course_id: course_id).where('position >= ?', position).each do |lesson|
      lesson.increment! :position
    end
  end

  def decrement_positions
    Lesson.where(course_id: course_id).where('position >= ?', position).each do |lesson|
      lesson.decrement! :position
    end
  end

  def send_lesson_notification
    ScheduleMaterialsUploadedNotificationWorker.perform_async(id)
  end

  def create_lesson_materials_uploaded_activity
    MaterialsUploadedActivityWorker.perform_async(id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < Users::BaseController
  before_filter :authenticate_user!
  before_action :find_lesson, only: [:show, :destroy]
  authorize_resource

  def show
    @homework = @lesson.homeworks.build
  end

  def index
    @lessons = course.lessons.by_position
  end

  def new
    @lesson = course.lessons.build
  end

  def create
    @lesson = course.lessons.build(lesson_params)
    @lesson.user_id = current_user.id

    if @lesson.save
      redirect_to dashboard_path, notice: 'Создан новый Урок.'
    else
      render :new
    end
  end

  def destroy
    @lesson.destroy

    redirect_to dashboard_path, notice: 'Урок удален!'
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :position, :description, :notes, :homework, :picture, :date)
  end

  def find_lesson
    @lesson ||= Lesson.find(params[:id])
  end

  def course
    @course ||= Course.find(params[:course_id])
  end

  helper_method :course
end

app/controllers/users/lessons_controller.rb
class Users::LessonsController < Users::BaseController
  before_action :find_lesson, only: [:destroy]

  def new
    @lesson = course.lessons.build
  end

  def create
    @lesson = course.lessons.build(lesson_params)
    @lesson.user_id = current_user.id

    if @lesson.save
      redirect_to dashboard_path, notice: 'Создан новый Урок.'
    else
      render :new
    end
  end

  def destroy
    @lesson.destroy

    redirect_to dashboard_path, notice: 'Урок удален!'
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :position, :description, :notes, :homework, :picture)
  end

  def find_lesson
    @lesson = Lesson.find(params[:id])
  end

  def course
    @course = Course.find(params[:course_id])
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def default_position
    course.lessons.count + 1
  end
end

app/views/lessons/_form.html.haml
= simple_form_for [:course, lesson] do |f|
  .box-body
    .form-group
      = f.input :title
    .form-group
      = f.input :position, collection: 1..default_position, selected: default_position
    .form-group
      = f.input :date
    .form-group
      = f.input :description
    .form-group
      = f.input :notes
    .form-group
      = f.input :homework
    .form-group
      = f.input :picture, as: :image_preview, input_html: { preview_version: :thumb }
      %p.help-block Выберите файл для добавления
    .box-footer
      = f.button :submit, 'Save', class: 'btn btn-primary btn-block btn-flat'

app/views/lessons/_homework_container.html.haml
- if lesson.user_homework(current_user)
  %h3 Your homework:
  %p= lesson.user_homework(current_user).body
  .pull-right
    = link_to 'View', homework_path(lesson, lesson.user_homework(current_user))

= simple_form_for([lesson, homework], url: homeworks_path(lesson), remote: true) do |f|
  #mynewpost.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'myModalLabel', role: 'dialog', tabindex: '-1'}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button'}
            %span{'aria-hidden' => 'true'} &times;
          %h4#myModalLabel.modal-title Send hometask
        .modal-body
          = f.error_notification
          .field
            = f.input :body, class: 'homework-body'
        .modal-footer
          %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Close
          = f.button :submit, 'Send', class: 'btn btn-primary'

app/views/lessons/index.html.haml
= provide(:title, 'Lessons')
%section.content
  .row
    .col-xs-12
      .box
        .box-header
          %h3.box-title
            %b
              "
              = course.title
              "
            course
            lessons:
        .box-body.table-responsive.no-padding
          %table.table.table-hover.fa-hover
            %tr
              %th Picture
              %th Position
              %th Title
              %th Date

            - @lessons.each do |lesson|
              %tr
                %td
                  .product-img
                    = image_tag(lesson.picture.admin_thumb, alt: 'Lesson picture')
                %td= lesson.position
                %td= link_to lesson.title, course_lesson_path(course, lesson)
                %td= lesson.date.strftime('%c')

app/views/lessons/new.html.haml
= provide(:title, 'Create new lesson.')

.content-header
  %h1
    Create new lesson.

%section.content
  .row
    .col-md-6.col-md-offset-3
      .box.box-primary
        .box-header.with-border
          %h3.box-title Create new lesson.
        = render 'form', lesson: @lesson

app/views/lessons/show.html.haml
= provide(:title, "#{@lesson.title}")

%section.content
  .row
    .col-md-offset-3.col-md-6
      .box.box-widget
        .box-header.with-border
          %h1= @lesson.title
          .user-block
            = image_tag 'user1-128x128.jpg', class: 'img-circle', alt: 'User profile picture'
            %span.username
              %a{href: '#'}
              -if @lesson.course.user.first_name
                = @lesson.course.user.full_name
              -else
                = @lesson.course.user.email
            %span.description
              = l(@lesson.created_at, format: '%d %B %Y')
        .box-body
          = image_tag(@lesson.picture.thumb, alt: 'Lesson photo', class: 'img-responsive pad center-block')
          %h3 Date
          %p= @lesson.date.strftime('%c')
          %h3 Description
          %p= @lesson.description
          %h3 Notes
          %p= @lesson.notes
          %h3 Hometask
          %p= @lesson.homework
          #homework_container
            = render 'homework_container', homework: @homework, lesson: @lesson
          #comments_container
            = render 'comments/comments_container', parent: @lesson, comment: current_user.comments.build
          .box-footer
            .row
              .col-md-4
                = link_to 'Back to lessons', course_lessons_path(course), class: 'btn btn-primary btn-block btn-flat'
              #send-button
                .col-md-offset-4.col-md-4
                  - unless @lesson.user_homework(current_user)
                    %button.btn.btn-success.btn-block.btn-flat{'data-target' => '#mynewpost', 'data-toggle' => 'modal', type: 'button'}
                      Send hometask