config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index do
        scope 'user', module: 'user' do
          resource :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
        end
      end
      resources :auth_tokens, only: :create
      resources :registrations, only: :create

      scope 'user/self', as: 'user', module: 'user' do
        resources :courses, only: :index, controller: :participated_courses
      end

      scope 'user/:id', as: 'authored', module: 'user' do
        resources :courses, only: :index, controller: :authored_courses
      end
    end
  end

  resources :courses, only: [:index, :show] do
    resource :subscriptions, only: [:create, :destroy], controller: :course_subscriptions
    resources :lessons, except: [:edit, :update]
  end

  namespace :users do
    resource :profile, only: [:edit, :update], controller: :profile
    resources :courses
    resources :activities, only: :index
  end

  scope module: 'users' do
    resource :dashboard, only: :show

    scope '/lessons/:lesson_id' do
      resources :homeworks, only: [:show, :index, :create] do
        member do
          put 'approve', to: 'homeworks#approve'
          put 'reject', to: 'homeworks#reject'
        end
      end
    end
  end

  resources :lessons, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  resources :homeworks, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  post '/courses/:course_id/participants/:user_id/expel', to: 'course_expulsions#create', as: :expel_course_participant

  root 'courses#index'
end

app/views/layouts/partials/_flash_messages.html.haml
- flash.each do |flash, msg|
  = content_tag :div, msg, class: "callout callout-#{alert_class_for(flash)}"

app/views/layouts/partials/_footer.html.haml
%footer.main-footer
  .pull-right.hidden-xs
    %b Version
    0.0.1
  %strong
    Copyright © Rubyboost 2016

app/views/layouts/partials/_header.html.haml
%header.main-header
  = link_to root_path do
    .logo
      %span.logo-mini RB
      %span.logo-lg Rubyboost
  %nav.navbar.navbar-static-top{:role => "navigation"}
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
    .navbar-custom-menu
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li.user.user-menu
            = link_to '#' do
              = image_tag 'user2-160x160.jpg', class: 'user-image', alt: 'User Image'
              %span.hidden-xs= current_user.email
          %li.user.user-menu
            = link_to destroy_user_session_path, method: :delete do
              Sign Out
        - else
          %li.user.user-menu
            = link_to new_user_registration_path do
              Sign Up
          %li.user.user-menu
            = link_to new_user_session_path do
              Sign In

app/views/layouts/partials/_sidebar.html.haml
%aside.main-sidebar
  %section.sidebar
    -if signed_in?
      .user-panel
        .pull-left.image
          = image_tag 'user2-160x160.jpg', class: 'img-circle'
        .pull-left.info
          -if current_user.first_name
            %p= current_user.full_name
          %a{href: '#'}
            %i.fa.fa-circle.text-success
            Online
    %form.sidebar-form{action: '#', method: 'get'}
      .input-group
        %input.form-control{name: 'q', placeholder: 'Search...', type: 'text'}
        %span.input-group-btn
          %button#search-btn.btn.btn-flat{name: 'search', type: 'submit'}
            %i.fa.fa-search
    %ul.sidebar-menu
      %li.header MAIN NAVIGATION
      - if signed_in?
        %li.active
          = link_to dashboard_path do
            %i.fa.fa-dashboard
            %span Dashboard
        %li
          =link_to edit_user_registration_path do
            %i.fa.fa-user
            %span Edit registration data
        %li
          =link_to edit_users_profile_path do
            %i.fa.fa-user
            %span Edit profile
        %li
          =link_to users_activities_path do
            %i.fa.fa-files-o
            %span My Feed
      %li
        = link_to courses_path do
          %i.fa.fa-files-o
          %span Courses